"""
Property-based tests for patient ID uniqueness.
Tests that all patient IDs generated by the system are unique.
"""

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from src.models.db_models import ArrivalModeEnum
from src.repositories.patient_repository import PatientRepository
from src.utils.database import get_test_db, create_test_database


class TestPatientIdUniqueness:
    """Property 2: Patient ID Uniqueness - Validates Requirements 1.4"""

    @pytest.fixture(autouse=True)
    def setup_test_db(self):
        """Set up clean test database for each test."""
        create_test_database()

    @given(
        arrival_modes=st.lists(
            st.sampled_from(ArrivalModeEnum),
            min_size=2,
            max_size=50
        ),
        acuity_levels=st.lists(
            st.integers(min_value=1, max_value=5),
            min_size=2,
            max_size=50
        )
    )
    @settings(max_examples=100)
    @pytest.mark.property_tests
    def test_patient_id_uniqueness_across_registrations(self, arrival_modes, acuity_levels):
        """
        Property 2: Patient ID Uniqueness
        Validates: Requirements 1.4

        For any set of patient registrations, all assigned patient IDs 
        should be unique across the system.
        """
        # Ensure we have the same number of arrival modes and acuity levels
        min_length = min(len(arrival_modes), len(acuity_levels))
        arrival_modes = arrival_modes[:min_length]
        acuity_levels = acuity_levels[:min_length]
        
        # Skip if we don't have enough data for a meaningful test
        if min_length < 2:
            return
        
        generated_patient_ids = set()
        created_patients = []
        
        # Use test database session
        db_session = next(get_test_db())
        try:
            repo = PatientRepository(db_session)
            
            # Create multiple patients and collect their IDs
            for arrival_mode, acuity_level in zip(arrival_modes, acuity_levels):
                # Let the repository generate the patient ID
                patient = repo.create(
                    patient_id=None,  # Let system generate ID
                    arrival_mode=arrival_mode,
                    acuity_level=acuity_level
                )
                
                created_patients.append(patient)
                
                # Check that this ID hasn't been seen before
                assert patient.patient_id not in generated_patient_ids, \
                    f"Duplicate patient ID generated: {patient.patient_id}"
                
                generated_patient_ids.add(patient.patient_id)
            
            # Verify all IDs are unique
            assert len(generated_patient_ids) == len(created_patients), \
                "Number of unique IDs doesn't match number of patients created"
            
            # Verify each patient can be retrieved by their unique ID
            for patient in created_patients:
                retrieved_patient = repo.get_by_id(patient.patient_id)
                assert retrieved_patient is not None, \
                    f"Could not retrieve patient with ID: {patient.patient_id}"
                assert retrieved_patient.patient_id == patient.patient_id
                
        finally:
            db_session.close()

    @given(
        num_patients=st.integers(min_value=10, max_value=100)
    )
    @settings(max_examples=50)
    @pytest.mark.property_tests
    def test_patient_id_generation_uniqueness(self, num_patients):
        """
        Property 2: Patient ID Uniqueness
        Validates: Requirements 1.4

        For any number of patient ID generations, all IDs should be unique
        even when generated in rapid succession.
        """
        db_session = next(get_test_db())
        try:
            repo = PatientRepository(db_session)
            generated_ids = set()
            
            # Generate multiple patient IDs rapidly
            for i in range(num_patients):
                patient_id = repo.generate_unique_patient_id()
                
                # Verify this ID hasn't been generated before
                assert patient_id not in generated_ids, \
                    f"Duplicate patient ID generated: {patient_id} (iteration {i})"
                
                generated_ids.add(patient_id)
                
                # Verify ID format (should start with 'P' and be reasonable length)
                assert patient_id.startswith('P'), \
                    f"Patient ID should start with 'P': {patient_id}"
                assert len(patient_id) >= 10, \
                    f"Patient ID should be at least 10 characters: {patient_id}"
                assert len(patient_id) <= 50, \
                    f"Patient ID should be at most 50 characters: {patient_id}"
            
            # Final verification: all IDs are unique
            assert len(generated_ids) == num_patients, \
                f"Expected {num_patients} unique IDs, got {len(generated_ids)}"
                
        finally:
            db_session.close()

    @given(
        patient_data=st.lists(
            st.tuples(
                st.sampled_from(ArrivalModeEnum),
                st.integers(min_value=1, max_value=5)
            ),
            min_size=5,
            max_size=20
        )
    )
    @settings(max_examples=50)
    @pytest.mark.property_tests
    def test_patient_id_uniqueness_with_database_persistence(self, patient_data):
        """
        Property 2: Patient ID Uniqueness
        Validates: Requirements 1.4

        For any set of patients created and persisted to database,
        all patient IDs should remain unique and retrievable.
        """
        db_session = next(get_test_db())
        try:
            repo = PatientRepository(db_session)
            created_patient_ids = []
            
            # Create and persist patients
            for arrival_mode, acuity_level in patient_data:
                patient = repo.create(
                    patient_id=None,  # Auto-generate
                    arrival_mode=arrival_mode,
                    acuity_level=acuity_level
                )
                created_patient_ids.append(patient.patient_id)
            
            # Verify all IDs are unique
            unique_ids = set(created_patient_ids)
            assert len(unique_ids) == len(created_patient_ids), \
                f"Found duplicate IDs: {len(created_patient_ids)} created, {len(unique_ids)} unique"
            
            # Verify all patients can be retrieved and exist in database
            for patient_id in created_patient_ids:
                assert repo.exists(patient_id), \
                    f"Patient ID {patient_id} should exist in database"
                
                retrieved_patient = repo.get_by_id(patient_id)
                assert retrieved_patient is not None, \
                    f"Should be able to retrieve patient {patient_id}"
                assert retrieved_patient.patient_id == patient_id, \
                    f"Retrieved patient ID should match: expected {patient_id}, got {retrieved_patient.patient_id}"
            
            # Verify total count matches
            total_count = repo.count()
            assert total_count >= len(created_patient_ids), \
                f"Database should contain at least {len(created_patient_ids)} patients, found {total_count}"
                
        finally:
            db_session.close()

    @pytest.mark.property_tests
    def test_patient_id_collision_handling(self):
        """
        Property 2: Patient ID Uniqueness
        Validates: Requirements 1.4

        Test that the system properly handles the rare case of ID collisions
        by generating alternative IDs.
        """
        db_session = next(get_test_db())
        try:
            repo = PatientRepository(db_session)
            
            # Generate a patient ID
            first_id = repo.generate_unique_patient_id()
            
            # Create a patient with this ID
            patient1 = repo.create(
                patient_id=first_id,
                arrival_mode=ArrivalModeEnum.AMBULANCE,
                acuity_level=3
            )
            
            # Try to create another patient with the same ID - should fail
            with pytest.raises(Exception):  # Should raise IntegrityError
                repo.create(
                    patient_id=first_id,
                    arrival_mode=ArrivalModeEnum.WALK_IN,
                    acuity_level=2
                )
            
            # Generate another ID - should be different
            second_id = repo.generate_unique_patient_id()
            assert second_id != first_id, \
                f"Second generated ID should be different: {first_id} vs {second_id}"
            
            # Should be able to create patient with second ID
            patient2 = repo.create(
                patient_id=second_id,
                arrival_mode=ArrivalModeEnum.WALK_IN,
                acuity_level=2
            )
            
            assert patient1.patient_id != patient2.patient_id, \
                "Two patients should have different IDs"
                
        finally:
            db_session.close()